---
language: python
python: "2.7"
rvm: 2.1.3

before_install:
  - "sudo apt-get update -qq"
  - gem update --system
  - gem --version

install:
  - "pip install ansible"
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local -vvvv --sudo"
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo | grep -q 'failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
  - "curl http://localhost/ | grep -q 'Hello World' && (echo 'Test Passed' && exit 0) || (echo 'Test Failed' && exit 1)"
